GET http://localhost:80/api/v1/lists

###

GET http://localhost:80/api/v1/list/1

###

POST http://localhost:80/api/v1/list
content-type: application/json

{
    "name": "oldlist"
}

###

PUT http://localhost:80/api/v1/list/1
content-type: application/json

{
    "name": "I'm the captain now"
}

###

DELETE http://localhost:80/api/v1/list/2
