// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/superlinkx/HomeList/app/model"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// AllItemsFromList provides a mock function with given fields: ctx, listID, limit, offset
func (_m *MockApp) AllItemsFromList(ctx context.Context, listID int64, limit int32, offset int32) ([]model.Item, error) {
	ret := _m.Called(ctx, listID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for AllItemsFromList")
	}

	var r0 []model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32, int32) ([]model.Item, error)); ok {
		return rf(ctx, listID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32, int32) []model.Item); ok {
		r0 = rf(ctx, listID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int32, int32) error); ok {
		r1 = rf(ctx, listID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_AllItemsFromList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllItemsFromList'
type MockApp_AllItemsFromList_Call struct {
	*mock.Call
}

// AllItemsFromList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - limit int32
//   - offset int32
func (_e *MockApp_Expecter) AllItemsFromList(ctx interface{}, listID interface{}, limit interface{}, offset interface{}) *MockApp_AllItemsFromList_Call {
	return &MockApp_AllItemsFromList_Call{Call: _e.mock.On("AllItemsFromList", ctx, listID, limit, offset)}
}

func (_c *MockApp_AllItemsFromList_Call) Run(run func(ctx context.Context, listID int64, limit int32, offset int32)) *MockApp_AllItemsFromList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockApp_AllItemsFromList_Call) Return(_a0 []model.Item, _a1 error) *MockApp_AllItemsFromList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_AllItemsFromList_Call) RunAndReturn(run func(context.Context, int64, int32, int32) ([]model.Item, error)) *MockApp_AllItemsFromList_Call {
	_c.Call.Return(run)
	return _c
}

// AllLists provides a mock function with given fields: ctx, limit, offset
func (_m *MockApp) AllLists(ctx context.Context, limit int32, offset int32) ([]model.List, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for AllLists")
	}

	var r0 []model.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]model.List, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []model.List); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_AllLists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllLists'
type MockApp_AllLists_Call struct {
	*mock.Call
}

// AllLists is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *MockApp_Expecter) AllLists(ctx interface{}, limit interface{}, offset interface{}) *MockApp_AllLists_Call {
	return &MockApp_AllLists_Call{Call: _e.mock.On("AllLists", ctx, limit, offset)}
}

func (_c *MockApp_AllLists_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *MockApp_AllLists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockApp_AllLists_Call) Return(_a0 []model.List, _a1 error) *MockApp_AllLists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_AllLists_Call) RunAndReturn(run func(context.Context, int32, int32) ([]model.List, error)) *MockApp_AllLists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItemOnList provides a mock function with given fields: ctx, listID, content, sort
func (_m *MockApp) CreateItemOnList(ctx context.Context, listID int64, content string, sort int64) (model.Item, error) {
	ret := _m.Called(ctx, listID, content, sort)

	if len(ret) == 0 {
		panic("no return value specified for CreateItemOnList")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) (model.Item, error)); ok {
		return rf(ctx, listID, content, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) model.Item); ok {
		r0 = rf(ctx, listID, content, sort)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, listID, content, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_CreateItemOnList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItemOnList'
type MockApp_CreateItemOnList_Call struct {
	*mock.Call
}

// CreateItemOnList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - content string
//   - sort int64
func (_e *MockApp_Expecter) CreateItemOnList(ctx interface{}, listID interface{}, content interface{}, sort interface{}) *MockApp_CreateItemOnList_Call {
	return &MockApp_CreateItemOnList_Call{Call: _e.mock.On("CreateItemOnList", ctx, listID, content, sort)}
}

func (_c *MockApp_CreateItemOnList_Call) Run(run func(ctx context.Context, listID int64, content string, sort int64)) *MockApp_CreateItemOnList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockApp_CreateItemOnList_Call) Return(_a0 model.Item, _a1 error) *MockApp_CreateItemOnList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_CreateItemOnList_Call) RunAndReturn(run func(context.Context, int64, string, int64) (model.Item, error)) *MockApp_CreateItemOnList_Call {
	_c.Call.Return(run)
	return _c
}

// CreateList provides a mock function with given fields: ctx, name
func (_m *MockApp) CreateList(ctx context.Context, name string) (model.List, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateList")
	}

	var r0 model.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.List, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.List); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.List)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_CreateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateList'
type MockApp_CreateList_Call struct {
	*mock.Call
}

// CreateList is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockApp_Expecter) CreateList(ctx interface{}, name interface{}) *MockApp_CreateList_Call {
	return &MockApp_CreateList_Call{Call: _e.mock.On("CreateList", ctx, name)}
}

func (_c *MockApp_CreateList_Call) Run(run func(ctx context.Context, name string)) *MockApp_CreateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApp_CreateList_Call) Return(_a0 model.List, _a1 error) *MockApp_CreateList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_CreateList_Call) RunAndReturn(run func(context.Context, string) (model.List, error)) *MockApp_CreateList_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItemFromList provides a mock function with given fields: ctx, listID, itemID
func (_m *MockApp) DeleteItemFromList(ctx context.Context, listID int64, itemID int64) error {
	ret := _m.Called(ctx, listID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItemFromList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, listID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_DeleteItemFromList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItemFromList'
type MockApp_DeleteItemFromList_Call struct {
	*mock.Call
}

// DeleteItemFromList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - itemID int64
func (_e *MockApp_Expecter) DeleteItemFromList(ctx interface{}, listID interface{}, itemID interface{}) *MockApp_DeleteItemFromList_Call {
	return &MockApp_DeleteItemFromList_Call{Call: _e.mock.On("DeleteItemFromList", ctx, listID, itemID)}
}

func (_c *MockApp_DeleteItemFromList_Call) Run(run func(ctx context.Context, listID int64, itemID int64)) *MockApp_DeleteItemFromList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockApp_DeleteItemFromList_Call) Return(_a0 error) *MockApp_DeleteItemFromList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_DeleteItemFromList_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockApp_DeleteItemFromList_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteList provides a mock function with given fields: ctx, listID
func (_m *MockApp) DeleteList(ctx context.Context, listID int64) error {
	ret := _m.Called(ctx, listID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, listID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_DeleteList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteList'
type MockApp_DeleteList_Call struct {
	*mock.Call
}

// DeleteList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
func (_e *MockApp_Expecter) DeleteList(ctx interface{}, listID interface{}) *MockApp_DeleteList_Call {
	return &MockApp_DeleteList_Call{Call: _e.mock.On("DeleteList", ctx, listID)}
}

func (_c *MockApp_DeleteList_Call) Run(run func(ctx context.Context, listID int64)) *MockApp_DeleteList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApp_DeleteList_Call) Return(_a0 error) *MockApp_DeleteList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_DeleteList_Call) RunAndReturn(run func(context.Context, int64) error) *MockApp_DeleteList_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemFromList provides a mock function with given fields: ctx, listID, itemID
func (_m *MockApp) GetItemFromList(ctx context.Context, listID int64, itemID int64) (model.Item, error) {
	ret := _m.Called(ctx, listID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetItemFromList")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (model.Item, error)); ok {
		return rf(ctx, listID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) model.Item); ok {
		r0 = rf(ctx, listID, itemID)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, listID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetItemFromList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemFromList'
type MockApp_GetItemFromList_Call struct {
	*mock.Call
}

// GetItemFromList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - itemID int64
func (_e *MockApp_Expecter) GetItemFromList(ctx interface{}, listID interface{}, itemID interface{}) *MockApp_GetItemFromList_Call {
	return &MockApp_GetItemFromList_Call{Call: _e.mock.On("GetItemFromList", ctx, listID, itemID)}
}

func (_c *MockApp_GetItemFromList_Call) Run(run func(ctx context.Context, listID int64, itemID int64)) *MockApp_GetItemFromList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockApp_GetItemFromList_Call) Return(_a0 model.Item, _a1 error) *MockApp_GetItemFromList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetItemFromList_Call) RunAndReturn(run func(context.Context, int64, int64) (model.Item, error)) *MockApp_GetItemFromList_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, listID
func (_m *MockApp) GetList(ctx context.Context, listID int64) (model.List, error) {
	ret := _m.Called(ctx, listID)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 model.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.List, error)); ok {
		return rf(ctx, listID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.List); ok {
		r0 = rf(ctx, listID)
	} else {
		r0 = ret.Get(0).(model.List)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, listID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockApp_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
func (_e *MockApp_Expecter) GetList(ctx interface{}, listID interface{}) *MockApp_GetList_Call {
	return &MockApp_GetList_Call{Call: _e.mock.On("GetList", ctx, listID)}
}

func (_c *MockApp_GetList_Call) Run(run func(ctx context.Context, listID int64)) *MockApp_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApp_GetList_Call) Return(_a0 model.List, _a1 error) *MockApp_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetList_Call) RunAndReturn(run func(context.Context, int64) (model.List, error)) *MockApp_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// ReflowList provides a mock function with given fields: ctx, listID
func (_m *MockApp) ReflowList(ctx context.Context, listID int64) error {
	ret := _m.Called(ctx, listID)

	if len(ret) == 0 {
		panic("no return value specified for ReflowList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, listID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_ReflowList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReflowList'
type MockApp_ReflowList_Call struct {
	*mock.Call
}

// ReflowList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
func (_e *MockApp_Expecter) ReflowList(ctx interface{}, listID interface{}) *MockApp_ReflowList_Call {
	return &MockApp_ReflowList_Call{Call: _e.mock.On("ReflowList", ctx, listID)}
}

func (_c *MockApp_ReflowList_Call) Run(run func(ctx context.Context, listID int64)) *MockApp_ReflowList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApp_ReflowList_Call) Return(_a0 error) *MockApp_ReflowList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_ReflowList_Call) RunAndReturn(run func(context.Context, int64) error) *MockApp_ReflowList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItemFromListChecked provides a mock function with given fields: ctx, listID, itemID, checked
func (_m *MockApp) UpdateItemFromListChecked(ctx context.Context, listID int64, itemID int64, checked bool) (model.Item, error) {
	ret := _m.Called(ctx, listID, itemID, checked)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItemFromListChecked")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) (model.Item, error)); ok {
		return rf(ctx, listID, itemID, checked)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) model.Item); ok {
		r0 = rf(ctx, listID, itemID, checked)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = rf(ctx, listID, itemID, checked)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_UpdateItemFromListChecked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItemFromListChecked'
type MockApp_UpdateItemFromListChecked_Call struct {
	*mock.Call
}

// UpdateItemFromListChecked is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - itemID int64
//   - checked bool
func (_e *MockApp_Expecter) UpdateItemFromListChecked(ctx interface{}, listID interface{}, itemID interface{}, checked interface{}) *MockApp_UpdateItemFromListChecked_Call {
	return &MockApp_UpdateItemFromListChecked_Call{Call: _e.mock.On("UpdateItemFromListChecked", ctx, listID, itemID, checked)}
}

func (_c *MockApp_UpdateItemFromListChecked_Call) Run(run func(ctx context.Context, listID int64, itemID int64, checked bool)) *MockApp_UpdateItemFromListChecked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(bool))
	})
	return _c
}

func (_c *MockApp_UpdateItemFromListChecked_Call) Return(_a0 model.Item, _a1 error) *MockApp_UpdateItemFromListChecked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_UpdateItemFromListChecked_Call) RunAndReturn(run func(context.Context, int64, int64, bool) (model.Item, error)) *MockApp_UpdateItemFromListChecked_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItemFromListContent provides a mock function with given fields: ctx, listID, itemID, content
func (_m *MockApp) UpdateItemFromListContent(ctx context.Context, listID int64, itemID int64, content string) (model.Item, error) {
	ret := _m.Called(ctx, listID, itemID, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItemFromListContent")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) (model.Item, error)); ok {
		return rf(ctx, listID, itemID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) model.Item); ok {
		r0 = rf(ctx, listID, itemID, content)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = rf(ctx, listID, itemID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_UpdateItemFromListContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItemFromListContent'
type MockApp_UpdateItemFromListContent_Call struct {
	*mock.Call
}

// UpdateItemFromListContent is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - itemID int64
//   - content string
func (_e *MockApp_Expecter) UpdateItemFromListContent(ctx interface{}, listID interface{}, itemID interface{}, content interface{}) *MockApp_UpdateItemFromListContent_Call {
	return &MockApp_UpdateItemFromListContent_Call{Call: _e.mock.On("UpdateItemFromListContent", ctx, listID, itemID, content)}
}

func (_c *MockApp_UpdateItemFromListContent_Call) Run(run func(ctx context.Context, listID int64, itemID int64, content string)) *MockApp_UpdateItemFromListContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockApp_UpdateItemFromListContent_Call) Return(_a0 model.Item, _a1 error) *MockApp_UpdateItemFromListContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_UpdateItemFromListContent_Call) RunAndReturn(run func(context.Context, int64, int64, string) (model.Item, error)) *MockApp_UpdateItemFromListContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItemFromListSort provides a mock function with given fields: ctx, listID, itemID, sort
func (_m *MockApp) UpdateItemFromListSort(ctx context.Context, listID int64, itemID int64, sort int64) (model.Item, error) {
	ret := _m.Called(ctx, listID, itemID, sort)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItemFromListSort")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) (model.Item, error)); ok {
		return rf(ctx, listID, itemID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) model.Item); ok {
		r0 = rf(ctx, listID, itemID, sort)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64) error); ok {
		r1 = rf(ctx, listID, itemID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_UpdateItemFromListSort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItemFromListSort'
type MockApp_UpdateItemFromListSort_Call struct {
	*mock.Call
}

// UpdateItemFromListSort is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - itemID int64
//   - sort int64
func (_e *MockApp_Expecter) UpdateItemFromListSort(ctx interface{}, listID interface{}, itemID interface{}, sort interface{}) *MockApp_UpdateItemFromListSort_Call {
	return &MockApp_UpdateItemFromListSort_Call{Call: _e.mock.On("UpdateItemFromListSort", ctx, listID, itemID, sort)}
}

func (_c *MockApp_UpdateItemFromListSort_Call) Run(run func(ctx context.Context, listID int64, itemID int64, sort int64)) *MockApp_UpdateItemFromListSort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockApp_UpdateItemFromListSort_Call) Return(_a0 model.Item, _a1 error) *MockApp_UpdateItemFromListSort_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_UpdateItemFromListSort_Call) RunAndReturn(run func(context.Context, int64, int64, int64) (model.Item, error)) *MockApp_UpdateItemFromListSort_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateList provides a mock function with given fields: ctx, listID, name
func (_m *MockApp) UpdateList(ctx context.Context, listID int64, name string) (model.List, error) {
	ret := _m.Called(ctx, listID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateList")
	}

	var r0 model.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (model.List, error)); ok {
		return rf(ctx, listID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) model.List); ok {
		r0 = rf(ctx, listID, name)
	} else {
		r0 = ret.Get(0).(model.List)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, listID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_UpdateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateList'
type MockApp_UpdateList_Call struct {
	*mock.Call
}

// UpdateList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - name string
func (_e *MockApp_Expecter) UpdateList(ctx interface{}, listID interface{}, name interface{}) *MockApp_UpdateList_Call {
	return &MockApp_UpdateList_Call{Call: _e.mock.On("UpdateList", ctx, listID, name)}
}

func (_c *MockApp_UpdateList_Call) Run(run func(ctx context.Context, listID int64, name string)) *MockApp_UpdateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockApp_UpdateList_Call) Return(_a0 model.List, _a1 error) *MockApp_UpdateList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_UpdateList_Call) RunAndReturn(run func(context.Context, int64, string) (model.List, error)) *MockApp_UpdateList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
