// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	app "github.com/superlinkx/HomeList/app"

	mock "github.com/stretchr/testify/mock"
)

// MockList is an autogenerated mock type for the list type
type MockList struct {
	mock.Mock
}

type MockList_Expecter struct {
	mock *mock.Mock
}

func (_m *MockList) EXPECT() *MockList_Expecter {
	return &MockList_Expecter{mock: &_m.Mock}
}

// AllLists provides a mock function with given fields: _a0, _a1
func (_m *MockList) AllLists(_a0 context.Context, _a1 int64) ([]app.List, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AllLists")
	}

	var r0 []app.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]app.List, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []app.List); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockList_AllLists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllLists'
type MockList_AllLists_Call struct {
	*mock.Call
}

// AllLists is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *MockList_Expecter) AllLists(_a0 interface{}, _a1 interface{}) *MockList_AllLists_Call {
	return &MockList_AllLists_Call{Call: _e.mock.On("AllLists", _a0, _a1)}
}

func (_c *MockList_AllLists_Call) Run(run func(_a0 context.Context, _a1 int64)) *MockList_AllLists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockList_AllLists_Call) Return(_a0 []app.List, _a1 error) *MockList_AllLists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockList_AllLists_Call) RunAndReturn(run func(context.Context, int64) ([]app.List, error)) *MockList_AllLists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateList provides a mock function with given fields: _a0, _a1
func (_m *MockList) CreateList(_a0 context.Context, _a1 string) (app.List, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateList")
	}

	var r0 app.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (app.List, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) app.List); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(app.List)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockList_CreateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateList'
type MockList_CreateList_Call struct {
	*mock.Call
}

// CreateList is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockList_Expecter) CreateList(_a0 interface{}, _a1 interface{}) *MockList_CreateList_Call {
	return &MockList_CreateList_Call{Call: _e.mock.On("CreateList", _a0, _a1)}
}

func (_c *MockList_CreateList_Call) Run(run func(_a0 context.Context, _a1 string)) *MockList_CreateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockList_CreateList_Call) Return(_a0 app.List, _a1 error) *MockList_CreateList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockList_CreateList_Call) RunAndReturn(run func(context.Context, string) (app.List, error)) *MockList_CreateList_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteList provides a mock function with given fields: _a0, _a1
func (_m *MockList) DeleteList(_a0 context.Context, _a1 int64) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockList_DeleteList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteList'
type MockList_DeleteList_Call struct {
	*mock.Call
}

// DeleteList is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *MockList_Expecter) DeleteList(_a0 interface{}, _a1 interface{}) *MockList_DeleteList_Call {
	return &MockList_DeleteList_Call{Call: _e.mock.On("DeleteList", _a0, _a1)}
}

func (_c *MockList_DeleteList_Call) Run(run func(_a0 context.Context, _a1 int64)) *MockList_DeleteList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockList_DeleteList_Call) Return(_a0 error) *MockList_DeleteList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockList_DeleteList_Call) RunAndReturn(run func(context.Context, int64) error) *MockList_DeleteList_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: _a0, _a1
func (_m *MockList) GetList(_a0 context.Context, _a1 int64) (app.List, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 app.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (app.List, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) app.List); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(app.List)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockList_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockList_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *MockList_Expecter) GetList(_a0 interface{}, _a1 interface{}) *MockList_GetList_Call {
	return &MockList_GetList_Call{Call: _e.mock.On("GetList", _a0, _a1)}
}

func (_c *MockList_GetList_Call) Run(run func(_a0 context.Context, _a1 int64)) *MockList_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockList_GetList_Call) Return(_a0 app.List, _a1 error) *MockList_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockList_GetList_Call) RunAndReturn(run func(context.Context, int64) (app.List, error)) *MockList_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateList provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockList) UpdateList(_a0 context.Context, _a1 int64, _a2 string) (app.List, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateList")
	}

	var r0 app.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (app.List, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) app.List); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(app.List)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockList_UpdateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateList'
type MockList_UpdateList_Call struct {
	*mock.Call
}

// UpdateList is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 string
func (_e *MockList_Expecter) UpdateList(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockList_UpdateList_Call {
	return &MockList_UpdateList_Call{Call: _e.mock.On("UpdateList", _a0, _a1, _a2)}
}

func (_c *MockList_UpdateList_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 string)) *MockList_UpdateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockList_UpdateList_Call) Return(_a0 app.List, _a1 error) *MockList_UpdateList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockList_UpdateList_Call) RunAndReturn(run func(context.Context, int64, string) (app.List, error)) *MockList_UpdateList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockList creates a new instance of MockList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockList(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockList {
	mock := &MockList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
