// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlite

import (
	"database/sql"
)

type List struct {
	ID   int64
	Name string
}

type ListItem struct {
	ID      int64
	ListID  int64
	Content sql.NullString
}
