openapi: "3.1.0"
info:
  title: HomeList
  version: "1"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:2552/api/v1
paths:
  /lists:
    $ref: "./paths/lists.yaml"
  /lists/{listID}:
    $ref: "./paths/list.yaml"
# security:
#   - BearerAuth: []
components:
  schemas:
    List:
      $ref: "./schemas/list.yaml"
  # securitySchemes:
  #   BearerAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  #     description: JWT token
